table_data column_formats bug fix if row contains None (#560)
This would previously fail with e.g.:
  TypeError: %i format: a number is required, not NoneType